name: publish
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: pre-commit/action@v3.0.0
     - uses: devcontainers/action@v1
       with:
         base-path-to-features: ./src
         features-namespace: ferronn-dev/features
         publish-features: "${{ github.ref == 'refs/heads/main' }}"
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
